# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .spec

# add or remove files that should be synced
synced_files:
    - .spec
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: playground
upstream_project_url: https://github.com/mmuzila/playground
